name: CI

on:
  push:
    branches:
      - main
      - new-branch

jobs:
  build:
    runs-on: windows-latest  # Run on Windows environment
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Display HTML Structure
      run: type changes.html  # Display the content of the HTML file for verification (Windows equivalent of cat)

    - name: Run HTML Validation
      uses: https://github.com/Fayaz117/temp_conv/blob/main/changes.html@v1
      with:
        path: changes.html  # Path to your HTML file

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install ESLint
      run: npm install eslint

    - name: Run JavaScript Linting
      run: |
        eslint changes.html  # Run linting on your JavaScript code

    - name: Run Unit Tests (if applicable)
      run: |
        # Add steps to run unit tests here, if you have any
