name: CI

on:
  push:
    branches:
      - main
      - new-branch

jobs:
  build:
    runs-on: windows-latest  # Run on Windows environment
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Display HTML Structure
      run: type changes.html  # Display the content of the HTML file for verification (Windows equivalent of cat)

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install ESLint
      run: npm install eslint --global  # Install ESLint globally

    - name: Run JavaScript Linting
      run: |
        # Find JavaScript files in the repository and lint them with ESLint
        find . -name "*.js" -exec eslint --parser-options '{"ecmaVersion": 2020}' {} +

    - name: Run Unit Tests (if applicable)
      run: |
        # Add steps to run unit tests here, if you have any
