name: CI

on:
  push:
    branches:
      - main
      - new-branch

jobs:
  build:
    runs-on: windows-latest  # Run on Windows environment
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Display HTML Structure
      run: type changes.html  # Display the content of the HTML file for verification (Windows equivalent of cat)

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install htmlhint
      run: npm install htmlhint --global  # Install htmlhint globally

    - name: Run HTML Linting
      run: htmlhint changes.html  # Run linting on your HTML code

    - name: Run Unit Tests (if applicable)
      run: |
        # Add steps to run unit tests here, if you have any
